[workspace]
members = [
    "mypl_cli",
    "mypl_lex",
    "mypl_ast",
    "mypl_parse",
    "mypl_interperter",
    "mypl_playground",
]

default-members = [
  "mypl_cli"
]

[workspace.dependencies]
anyhow = "1.0.71"
regex = "1.3.7"
thiserror = "1.0.40"
