[package]
name = "mypl-compiler"
version = "0.1.0"
authors = ["tglanz"]
edition = "2018"

[dependencies]
log = "0.4.8"
log4rs = "0.12.0"
mypl-cli = { path = "../mypl-cli" }
mypl-lex = { path = "../mypl-lex" }