[package]
name = "mypl_ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mypl_lex = { path = "../mypl_lex" }
anyhow.workspace = true
serde.workspace = true
ron.workspace = true
